name: osmos
description: A diabetes management application
publish_to: 'none'


environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^6.0.3
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.7
  record: ^6.0.0
  googleapis: ^13.0.0 
  googleapis_auth: ^1.4.1 
  audioplayers: ^5.2.1
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  camera: ^0.11.1
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Screenshot_1.png
fonts:
  - family: League Spartan
    fonts:
      - asset: assets/fonts/LeagueSpartan-Regular.ttf
      - asset: assets/fonts/LeagueSpartan-Medium.ttf
        weight: 500
      - asset: assets/fonts/LeagueSpartan-Light.ttf
        weight: 300