// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzMaGaD4ewZsc7s9TmcDnA3D2loEIcziM',
    appId: '1:1072116166304:web:36f48c7b12fe3acb1763c5',
    messagingSenderId: '1072116166304',
    projectId: 'osmoshealthapp',
    authDomain: 'osmoshealthapp.firebaseapp.com',
    storageBucket: 'osmoshealthapp.firebasestorage.app',
    measurementId: 'G-Z380BEGPS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7b71CZ6o8sedINZIKzAlI8r5fA3Qfhg',
    appId: '1:1072116166304:android:690d3163396728a91763c5',
    messagingSenderId: '1072116166304',
    projectId: 'osmoshealthapp',
    storageBucket: 'osmoshealthapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzA6a3uBzS9I6a6nxrQVGLzr7FMlu_Las',
    appId: '1:1072116166304:ios:c0a30ca7f8d099671763c5',
    messagingSenderId: '1072116166304',
    projectId: 'osmoshealthapp',
    storageBucket: 'osmoshealthapp.firebasestorage.app',
    iosClientId: '1072116166304-v3je2fcejek1623e60f9cv8nmnli9vj0.apps.googleusercontent.com',
    iosBundleId: 'com.osmos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzMaGaD4ewZsc7s9TmcDnA3D2loEIcziM',
    appId: '1:1072116166304:web:38da14da45c852a91763c5',
    messagingSenderId: '1072116166304',
    projectId: 'osmoshealthapp',
    authDomain: 'osmoshealthapp.firebaseapp.com',
    storageBucket: 'osmoshealthapp.firebasestorage.app',
    measurementId: 'G-FTDW53VGYF',
  );
}
